.github/workflows/docker-image.yml

Want to create a prow scripts image to use in the prow system in quay

Adding image push workflow

---

Dockerfile

adding quay krkn chaos image for from

---

container-scenarios/prow_run.sh
cpu-hog/prow_run.sh
io-hog/prow_run.sh
namespace-scenarios/prow_run.sh
network-chaos/prow_run.sh
node-disruptions/prow_run.sh
pod-scenarios/prow_run.sh
pvc-scenario/prow_run.sh

Cant write to main krkn-hub folder, need to use envsubst to a tmp folder

Adding tmp in more files

---

container-scenarios/prow_run.sh
cpu-hog/prow_run.sh
io-hog/prow_run.sh
memory-hog/prow_run.sh
namespace-scenarios/prow_run.sh
network-chaos/prow_run.sh
node-disruptions/prow_run.sh
pod-scenarios/prow_run.sh
power-outage/prow_run.sh
pvc-scenario/prow_run.sh
time-scenarios/prow_run.sh

Want to use the new report location to use in prow systems 
https://github.com/krkn-chaos/krkn/pull/564

Tmp output

---

pod-network-chaos/prow_run.sh

Missed one of the prow run scripts when porting over from krkn-hub

Adding pod network run script

---

container-scenarios/prow_run.sh

Incorrect git clone

---

Dockerfile

Want to add execute option for all prow_run files

Execute prow_script

---

README.md

Updating day to push to this repo so prow can get latest version

adding updated day

---

network-chaos/prow_run.sh

Update network chaos script

---

pod-network-chaos/prow_run.sh

Updating pod network script

---

README.md

Updating item in readme to get a push to main branch

Updating readme for push to main

---

README.md

Adding readme updates

---

README.md

Need to get updates in krkn and krkn-hub into prow

Updating readme to get service hijack 

---

zone-outages/prow_run.sh

Failure, dont have write permission at current folder. Need tmp output file location https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/52576/rehearse-52576-periodic-ci-redhat-chaos-prow-scripts-main-4.16-nightly-krkn-hub-zone-tests/1795886783146233856

Need -o option

---

application-outages/prow_run.sh
container-scenarios/prow_run.sh
cpu-hog/prow_run.sh
io-hog/prow_run.sh
memory-hog/prow_run.sh
namespace-scenarios/prow_run.sh
network-chaos/prow_run.sh
node-disruptions/prow_run.sh
pod-network-chaos/prow_run.sh
pod-scenarios/prow_run.sh
power-outage/prow_run.sh
pvc-scenario/prow_run.sh
time-scenarios/prow_run.sh
zone-outages/prow_run.sh

Reverts redhat-chaos/prow-scripts#28

Revert "Add executable permissions to krkn dir"

---

.github/workflows/auto_push.yml
README.md

Want to add this manual action that will allow us to call this from krkn/krkn-hub that will update the prow image when a new update is pushed to one of those repos

Readme auto update

---

zone-outages/prow_run.sh

```
+ python3.9 /root/kraken/run_kraken.py --config=/tmp/zone_config.yaml -o /tmp/report.out
python3.9: can't open file '/root/kraken/run_kraken.py': [Errno 2] No such file or directory
```

Changing folder from main to krkn

---

.github/workflows/auto_push.yml
README.md

Trying to add write permissions 
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

Adding write permissions

---

node-disruptions/prow_run.sh

Need same change I added to kraken-hub here since we dontuse the run.sh script in prow

Ibm verify node blank

---

container-scenarios/prow_run.sh
pod-scenarios/prow_run.sh
time-scenarios/prow_run.sh

Tweak container and time scenarios to use them for Sippy to scrape them.

Add junit xml parameters

---

container-scenarios/prow_run.sh
namespace-scenarios/prow_run.sh
power-outage/prow_run.sh

Taking out double list because we no longer have post actions
In conjunction with this change: https://github.com/krkn-chaos/krkn-hub/pull/209

Taking out double list

---

cpu-hog/prow_run.sh
io-hog/prow_run.sh
memory-hog/prow_run.sh

Moving things around and trying to use more variables to keep consistent 
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/57555/rehearse-57555-periodic-ci-redhat-chaos-prow-scripts-main-4.18-nightly-krkn-hub-cloud-gcp-node-tests/1846315894695792640

Hog scenario

---

cpu-hog/prow_run.sh

Small fix for using variable instead of string https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/57445/rehearse-57445-periodic-ci-redhat-chaos-prow-scripts-main-rosa-4.17-nightly-krkn-rosa-hcp-node/1846934698392031232

Variable of cpu

---

node-disruptions/prow_run.sh

Correlating pr to krkn-hub: https://github.com/krkn-chaos/krkn-hub/pull/211/files

Adding ibm node scenario type

---

syn-flood/prow_run.sh

https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/59426/rehearse-59426-pull-ci-redhat-chaos-prow-scripts-main-4.18-nightly-krkn-hub-syn-flood/1864780215322939392
Scenario file not found because not properly overwriting it from template to yaml

Adding tmp scenario file

---

cpu-hog/prow_run.sh
io-hog/prow_run.sh
memory-hog/prow_run.sh

Updating hog scenario template files
Error seen here:https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-redhat-chaos-prow-scripts-main-4.15-nightly-krkn-hub-node-tests-415/1887713312439799808/artifacts/krkn-hub-node-tests-415/redhat-chaos-hog-scenarios-memory/build-log.txt

Adding hog scenario updates

---

zone-outages/slos

Scenario centric profile is needed for zone-outages where failures are expected during the run.

Add slo profile for zone-outages

---

node-disruptions/prow_run.sh

similar to : https://github.com/krkn-chaos/krkn-hub/pull/242

Taking out plugin from ibm and vmware node

---

zone-outages/prow_run.sh

Adding gcp option for zone outage

Adding gcp zone type

---

cerberus/prow_run.sh

Moving option to maybe not print kubeconfig

Moving -x option
